using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using UsersManager.Presenters;
using UsersManager.View;

namespace UsersManager
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window, IViewMainWindow
    {
        private IPresenterMainWindow _presenter;
        private List<int> filtersId;

        public MainWindow()
        {
            InitializeComponent();
            _presenter = new PresenterMainWindow(this);
            filtersId = new List<int>();
        }

        private void MenuItemAddUser_OnClick(object sender, RoutedEventArgs e)
        {
            _presenter.AddUser();
        }

        private void MenuItemCategories_Click(object sender, RoutedEventArgs e)
        {
            _presenter.Categories();
        }

        private void CheckBoxCategories_StateChanged(object sender, RoutedEventArgs e)
        {
            var isChecked = ((CheckBox)sender).IsChecked;
            if (isChecked != null && (bool) isChecked)
            {
                filtersId.Add(((Category)((CheckBox)sender).DataContext).Id);
            }
            else
            {
                if (isChecked != null)
                {
                    filtersId.RemoveAt(filtersId.FindIndex(a => a == ((Category)((CheckBox)sender).DataContext).Id));
                }
            }
            _presenter.CategoriesCheckBox_ChangeState(filtersId);
        }

        public DataGrid MainDataGrid { get => DataGrid; set => DataGrid = value; }
        public ListBox CategoriesListBox { get => ListBoxCategories; set => ListBoxCategories = value; }

        private void MyListView_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            throw new NotImplementedException();
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            _presenter.AddCategoryColumn();
        }

        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            _presenter.CommitChanges();
        }

        private void DataGrid_SourceUpdated(object sender, DataTransferEventArgs e)
        {
            //DataGridComboBoxColumn comboBoxColumn = (DataGridComboBoxColumn)DataGrid.Columns[DataGrid.Columns.Count - 1];
            //comboBoxColumn.ItemsSource = ListBoxCategories.ItemsSource;
            
        }

        private void DataGrid_OnBeginningEdit(object sender, DataGridBeginningEditEventArgs e)
        {
            if (DataGrid.SelectedCells[0].Column.Header.Equals("Category"))
            {
                _presenter.ChooseCategoryWindow(DataGrid.SelectedCells[0]);
            }
        }
    }
}
